PREDEFINED_CATEGORIES = [
    # Core Sciences
    "Physics",
    "Chemistry",
    "Biology",
    "Astronomy",
    "Earth Science",
    "Environmental Science",
    "Geology",
    "Meteorology",
    "Oceanography",
    "Mathematics",
    "Statistics",
    "Computer Science",
    "Data Science",
    "Artificial Intelligence",
    "Neuroscience",
    "Psychology",
    "Sociology",
    "Anthropology",
    "Economics",
    "Political Science",
    "Linguistics",
    "Philosophy",
    "History",
    "Archaeology",
    "Geography",
    "Ecology",
    "Genetics",
    "Biotechnology",
    "Biochemistry",
    "Molecular Biology",
    "Microbiology",
    "Zoology",
    "Botany",
    "Medicine",
    "Pharmacology",
    "Immunology",
    "Astrophysics",
    "Quantum Mechanics",
    "Thermodynamics",
    "Materials Science",
    "Engineering",
    "Robotics",
    "Nanotechnology",
    "Cognitive Science",
    "Behavioral Science",
    "Climatology",
    "Hydrology",
    "Astrobiology",
    "Biophysics",
    "Chemical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Aerospace Engineering",
    "Biomedical Engineering",
    "Environmental Engineering",
    "Nuclear Physics",
    "Particle Physics",
    "Condensed Matter Physics",
    "Optics",
    "Acoustics",
    "Fluid Dynamics",
    "Geophysics",
    "Geochemistry",
    "Evolutionary Biology",
    "Marine Biology",
    "Cell Biology",
    "Developmental Biology",
    "Systems Biology",
    "Bioinformatics",
    "Synthetic Biology",
    "Agricultural Science",
    "Food Science",
    "Veterinary Science",
    "Epidemiology",
    "Public Health",
    "Toxicology",
    "Structural Biology",
    "Planetary Science",
    "Space Science",
    "Cosmology",
    "Theoretical Physics",
    "Applied Mathematics",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Cybersecurity",
    "Software Engineering",
    "Quantum Computing",
    "Renewable Energy",
    "Energy Storage",
    "Climate Science",
    "Sustainability Science",
    "Conservation Biology",
    "Wildlife Biology",
    "Soil Science",
    "Urban Planning",
    "Transportation Science",
    "Remote Sensing",
    "Geographic Information Systems (GIS)",
    "Demography",
    "Criminology",
    "Social Work",
    "Communication Studies",
    "Media Studies",
    "Cultural Studies",
    "Gender Studies",
    "Religious Studies",
    "Art History",
    "Musicology",
    "Forensic Science",
    "Digital Humanities",
    "Ethics",
    "Logic",
    "Epistemology",
    "Metaphysics",
    "Aesthetics",
    "Political Economy",
    "International Relations",
    "Public Policy",
    "Urban Studies",
    "Development Studies",
    "Global Health",
    "Health Informatics",
    "Medical Imaging",
    "Rehabilitation Science",
    "Sports Science",
    "Exercise Physiology",
    "Nutrition Science",
    "Gerontology",
    "Dentistry",
    "Optometry",
    "Alternative Medicine",
    "Space Exploration",
    "Astrodynamics",
    "Satellite Technology",
    "Exoplanetology",
    "Stellar Astronomy",
    "Galactic Astronomy",
    "Extragalactic Astronomy",
    "Dark Matter",
    "Dark Energy",
    "Quantum Field Theory",
    "String Theory",
    "General Relativity",
    "Special Relativity",
    "Chaos Theory",
    "Complex Systems",
    "Game Theory",
    "Decision Theory",
    "Control Theory",
    "Signal Processing",
    "Image Processing",
    "Speech Processing",
    "Computational Linguistics",
    "Ethnography",
    "Primatology",
    "Ornithology",
    "Entomology",
    "Ichthyology",
    "Herpetology",
    "Mammalogy",
    "Mycology",
    "Virology",
    "Parasitology",
    "Health Economics",
    "Health Policy",
    "Health Systems",
    "Telemedicine",
    "Medical Ethics",
    "Bioethics",
    "Environmental Ethics",
    "Climate Ethics",
    "Science Communication",
    "Science Education",
    "Philosophy of Science",
    "Science Policy",
    "Innovation Studies",
    "Technology Management",
    "Intellectual Property",
    "Science and Law",
    "Science and Religion",
    "Science and Art",
    "Science and Literature",
    "Science and Philosophy",
    "Science and Ethics",
    "Science and Society",
    "Science and Technology",
    "Science and Innovation",
    "Science and Policy",
    "Science and Education",
    "Science and Communication",
    "Science and Culture"
]