PREDEFINED_CATEGORIES = [
    # Core Sciences
    "Physics",
    "Chemistry",
    "Biology",
    "Astronomy",
    "Earth Science",
    "Environmental Science",
    "Geology",
    "Meteorology",
    "Oceanography",
    "Paleontology",
    "Mathematics",
    "Statistics",
    "Computer Science",
    "Information Science",
    "Data Science",
    "Artificial Intelligence",
    "Neuroscience",
    "Psychology",
    "Sociology",
    "Anthropology",
    "Economics",
    "Political Science",
    "Linguistics",
    "Philosophy",
    "History",
    "Archaeology",
    "Geography",
    "Ecology",
    "Genetics",
    "Biotechnology",
    "Biochemistry",
    "Molecular Biology",
    "Microbiology",
    "Zoology",
    "Botany",
    "Medicine",
    "Pharmacology",
    "Immunology",
    "Astrophysics",
    "Quantum Mechanics",
    "Thermodynamics",
    "Materials Science",
    "Engineering",
    "Robotics",
    "Nanotechnology",
    "Cognitive Science",
    "Behavioral Science",
    "Climatology",
    "Hydrology",
    "Volcanology",

    # Additional Sciences and Subfields
    "Astrobiology",
    "Biophysics",
    "Chemical Engineering",
    "Civil Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Aerospace Engineering",
    "Biomedical Engineering",
    "Environmental Engineering",
    "Nuclear Physics",
    "Particle Physics",
    "Condensed Matter Physics",
    "Optics",
    "Acoustics",
    "Fluid Dynamics",
    "Geophysics",
    "Geochemistry",
    "Paleobiology",
    "Evolutionary Biology",
    "Marine Biology",
    "Cell Biology",
    "Developmental Biology",
    "Systems Biology",
    "Computational Biology",
    "Bioinformatics",
    "Synthetic Biology",
    "Agricultural Science",
    "Food Science",
    "Veterinary Science",
    "Epidemiology",
    "Public Health",
    "Toxicology",
    "Pharmacogenomics",
    "Structural Biology",
    "Cryobiology",
    "Ethnobotany",
    "Paleoclimatology",
    "Seismology",
    "Mineralogy",
    "Petrology",
    "Geomorphology",
    "Planetary Science",
    "Space Science",
    "Cosmology",
    "Theoretical Physics",
    "Applied Mathematics",
    "Computational Mathematics",
    "Mathematical Physics",
    "Operations Research",
    "Cryptography",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Cybersecurity",
    "Human-Computer Interaction",
    "Software Engineering",
    "Database Systems",
    "Network Science",
    "Quantum Computing",
    "Renewable Energy",
    "Energy Storage",
    "Climate Science",
    "Sustainability Science",
    "Conservation Biology",
    "Wildlife Biology",
    "Forestry",
    "Soil Science",
    "Hydroponics",
    "Aquaculture",
    "Urban Planning",
    "Transportation Science",
    "Remote Sensing",
    "Geographic Information Systems (GIS)",
    "Cartography",
    "Demography",
    "Criminology",
    "Social Work",
    "Communication Studies",
    "Media Studies",
    "Cultural Studies",
    "Gender Studies",
    "Religious Studies",
    "Art History",
    "Musicology",
    "Literary Theory",
    "Comparative Literature",
    "Classical Studies",
    "Museum Studies",
    "Heritage Studies",
    "Forensic Science",
    "Criminalistics",
    "Digital Humanities",
    "Science and Technology Studies",
    "Ethics",
    "Logic",
    "Epistemology",
    "Metaphysics",
    "Aesthetics",
    "Political Economy",
    "International Relations",
    "Public Policy",
    "Urban Studies",
    "Development Studies",
    "Global Health",
    "Health Informatics",
    "Medical Imaging",
    "Rehabilitation Science",
    "Sports Science",
    "Exercise Physiology",
    "Nutrition Science",
    "Gerontology",
    "Palliative Care",
    "Dentistry",
    "Optometry",
    "Chiropractic",
    "Alternative Medicine",
    "Traditional Medicine",
    "Space Exploration",
    "Astrodynamics",
    "Satellite Technology",
    "Space Medicine",
    "Exoplanetology",
    "Stellar Astronomy",
    "Galactic Astronomy",
    "Extragalactic Astronomy",
    "Cosmic Rays",
    "Dark Matter",
    "Dark Energy",
    "Quantum Field Theory",
    "String Theory",
    "General Relativity",
    "Special Relativity",
    "Chaos Theory",
    "Complex Systems",
    "Game Theory",
    "Decision Theory",
    "Control Theory",
    "Signal Processing",
    "Image Processing",
    "Speech Processing",
    "Computational Linguistics",
    "Semiotics",
    "Ethnography",
    "Ethnology",
    "Primatology",
    "Ornithology",
    "Entomology",
    "Ichthyology",
    "Herpetology",
    "Mammalogy",
    "Mycology",
    "Virology",
    "Parasitology",
    "Epidemiology",
    "Public Health",
    "Health Economics",
    "Health Policy",
    "Health Systems",
    "Health Informatics",
    "Telemedicine",
    "Medical Ethics",
    "Bioethics",
    "Environmental Ethics",
    "Climate Ethics",
    "Science Communication",
    "Science Education",
    "History of Science",
    "Philosophy of Science",
    "Sociology of Science",
    "Anthropology of Science",
    "Science Policy",
    "Innovation Studies",
    "Technology Management",
    "Intellectual Property",
    "Science and Law",
    "Science and Religion",
    "Science and Art",
    "Science and Literature",
    "Science and Philosophy",
    "Science and Ethics",
    "Science and Society",
    "Science and Technology",
    "Science and Innovation",
    "Science and Policy",
    "Science and Education",
    "Science and Communication",
    "Science and Culture",
    "Science and History",
    "Science and Future Studies"
]